### PR TITLE
Update wording & add a favicon.ico

### PR DESCRIPTION
**Pull request by erayrafet**

### CODE REVIEW

**Comment by ShankarBUS** [comment]
We have an official icon in the app repo.

Is this the same from the app repo?

**Comment by erayrafet** [comment]
Yeah. I snatched a 1024px png and converted it to .ico since it works everywhere.

**Comment by ShankarBUS** [comment]
Well the official *.ico has every required resolution (I even did a pixel art for 16x16).

So, we should use that.

**Comment by erayrafet** [comment]
> Well the official *.ico has every required resolution (I even did a pixel art for 16x16).
> 
> So, we should use that.

Where can we find it?

**Comment by ShankarBUS** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/ModernFlyouts/Assets/Logo.ico

**Comment by erayrafet** [comment]
image
It won't load in Chrome.

**Comment by erayrafet** [comment]
At least, the current favicon works. I don't think anyone needs 16x16 since browsers are smart enough to downscale when needed.

**Pull request merged**
