### PR TITLE
redesign

### PR DESCRIPTION
**Pull request by tropicaaal**
# i was bored, alright

https://user-images.githubusercontent.com/42101043/103683154-704c6e80-4f4f-11eb-94a0-2e5aa79e5d24.mp4

### CODE REVIEW

**Comment by tropicaaal** [comment]
Wanted to mess around with some WinUI component recreations i made this summer, so I decided to use those on the site (made recreating the flyout and buttons especially easy.)

**Comment by tropicaaal** [comment]
Anything you need or want changed I can do.

**Comment by ShankarBUS** [comment]
Bruh! Are you kidding me? That's insane!
Awesome!

So, @FJduFou made this #4, https://fjdufou.github.io/

Now I can't decide between both of your work.
I know both of you spent your efforts on the website. But I can't reject one. I don't wanna make you sad.
Could you please do a collab?

**Comment by FJduFou** [comment]
> Bruh! Are you kidding me? That's insane!
> Awesome!
> 
> So, @FJduFou made this #4, https://fjdufou.github.io/
> 
> Now I can't decide between both of your work.
> I know both of you spent your efforts on the website. But I can't reject one. I don't wanna make you sad.
> Could you please do a collab?

No! This PR is rly better, i have close, amazing job Tropix!

**Comment by ShankarBUS** [comment]
So, now this is messed.

I shouldn't let your efforts in vain. It hurts me to reject one. Guys please collab and make me happy.

**Comment by FJduFou** [comment]
> So, now this is messed.
> 
> I shouldn't let your efforts in vain. It hurts me to reject one. Guys please collab and make me happy.

Why would I want to add my horror to this masterpiece?
No, this site is perfect, it is light, interactive, fluent ... nothing better

**Comment by ShankarBUS** [comment]
Ughhh! Fine, I'll merge this one

**Comment by ShankarBUS** [comment]
So, guys I would like to add you (@Tropix126 and @FJduFou) as a collaborator of this repo.

Are you okay with it?
This way you can commit directly without making a PR.

**Comment by tropicaaal** [comment]
> So, guys I would like to add you (@Tropix126 and @FJduFou) as a collaborator of this repo.
> 
> Are you okay with it?
> This way you can commit directly without making a PR.

I'm fine with that. I've got his discord in case we need to be in close contact.

**Comment by ShankarBUS** [comment]
Join the server please?

**Comment by ShankarBUS** [comment]
> I've got his discord in case 

Wait whose discord? With @FJduFou?

**Comment by tropicaaal** [comment]
> > I've got his discord in case
> 
> Wait whose discord? With @FJduFou?

Yeah, do you guys have a server? I'm in zeealeid's and talk there (semi) frequently.

**Comment by ShankarBUS** [comment]
Yes. Join now -> https://discord.gg/TcYskeyaYE

**Pull request merged**
