### PR TITLE
Update wording

### PR DESCRIPTION
**Pull request by erayrafet**

### CODE REVIEW

**Comment by FJduFou** [comment]
As for me, replace **Grab from the Microsoft Store** by **Get from the Microsoft Store**

**Comment by Cyberdroid1** [comment]
Is grab a suitable word?

**Comment by prakharb5** [comment]
How about
Get "it" from microsoft store?

**Comment by FJduFou** [comment]
> Get "it" from ms store?

Yes, why not, `Get it from the Microsoft Store`

**Comment by prakharb5** [comment]
Yup

**Comment by erayrafet** [comment]
> > Get "it" from ms store?
> 
> Yes, why not, `Get it from the Microsoft Store`

That's better.

**Comment by FJduFou** [comment]
> > > Get "it" from ms store?
> > 
> > 
> > Yes, why not, `Get it from the Microsoft Store`
> 
> That's better.

I just wait you update this and I merge

**Comment by prakharb5** [comment]
Wait, is this to be merged?

**Comment by FJduFou** [comment]
> Wait, is this to be merged?

#8

**Comment by erayrafet** [comment]
No. Merge #8 instead

**Pull request closed without merging**
