### PR TITLE
Add mobile support

### PR DESCRIPTION
**Pull request by tropicaaal**
# Before:
image
# After:
image

### CODE REVIEW

**Comment by tropicaaal** [comment]
Quick clarification: The rounding of the image in my second screenshot was just me messing around and isn't included in the actual PR.

**Comment by tropicaaal** [comment]
I've also cleaned up some unused code and swapped to CSS vars (in case you want to easily switch around colors).

**Comment by prakharb5** [comment]
Actually, I feel Rounded corners look good!

**Comment by ShankarBUS** [comment]
Rounded corners please!

**Comment by tropicaaal** [comment]
> Rounded corners please!

Updated to include rounding on the image.

**Comment by prakharb5** [comment]
@Tropix126 
Is this PR ready? I am going to merge it.

**Review by Samuel12321 — APPROVED** [review]
Looks great, thanks so much.

Will merge this now.

**Comment by ShankarBUS** [comment]
Ummm, guys the website is broken.
image

**Comment by ShankarBUS** [comment]
This is because the `bootstrap-reboot.min.css` and the `style.css` were being referenced in wrong urls.

I'll fix that.

**Comment by ShankarBUS** [comment]
GitHub keeps adding un-necessary stuffs to the `index.html`. Any ideas how to prevent it?

The styles are also not being applied properly.

**Comment by prakharb5** [comment]
Umm...

**Comment by ShankarBUS** [comment]
There's no padding and the image doesn't have rounded borders

**Comment by tropicaaal** [comment]
Messed up a class. On line 35, 
```css
#hero img {
```
should be 
```css
.item img {
```

**Comment by tropicaaal** [comment]
Can make a PR if needed

**Pull request merged**
