### PR TITLE
Rick Astley - Never Gonna Give You Up & separate volume control slider

### PR DESCRIPTION
**Pull request by erayrafet**

### CODE REVIEW

**Comment by tropicaaal** [comment]
looks good.

**Comment by erayrafet** [comment]
Thanks for merging this. I hope the Rick Astley fanboy is happy.

**Comment by erayrafet** [comment]
Later on, from time to time, we could change the song to something else.

**Comment by prakharb5** [comment]
> Thanks for merging this. I hope the Rick Astley fanboy is happy.

Thanks dude! We need to rickroll everyone in this world.

**Pull request merged**
