### PR TITLE
Add cursor transform to Buttons, Links and Input

### PR DESCRIPTION
**Pull request by kimlimjustin**
Add cursor transforms to Buttons, Link, and Input as follows:
- Pointer cursor for Buttons and Link (Github Corner)
- All scroll cursor for Input range (Volume slider)

Images (some of those updates):
| Before | After |
| ------ | ------ |
| Before | After |
| Before | WhatsApp Image 2021-02-24 at 14 29 25 |

### CODE REVIEW

**Comment by prakharb5** [comment]
@FJduFou

**Comment by FJduFou** [comment]
For volume slider, use Sizeew and not Sizeall please...
Else, good idea!
image

**Comment by kimlimjustin** [comment]
> For volume slider, use Sizeew and not Sizeall please...
> Else, good idea!
> image

Okay, updated! Btw, it's `w-resize` xd.

**Comment by FJduFou** [comment]
Ok, i merge

**Pull request merged**
